"""Tier-3 sandbox: NVIDIA OpenShell — policy-governed agent runtime.

OpenShell (https://github.com/NVIDIA/OpenShell, Apache-2.0) is a runtime that
executes workloads inside isolated, policy-governed sandboxes (Docker / Podman
/ microVM / k8s backends) behind a Gateway control plane. Beyond what our
tier-2 ContainerSandbox offers it adds the two things container.py explicitly
punts on:

  1. A REAL egress allowlist (hot-reloadable network policy) — so a
     CodeExecSpec.network="allowlist" run can reach a named set of hosts
     (by default ONLY the local inference endpoints) instead of being
     downgraded to deny.
  2. An *inference* policy domain (the "privacy router") — agent/tool code may
     reach ONLY the local model backend and can never egress to a cloud LLM,
     turning Enclave's "no cloud inference, all data local" principle into a
     policy-enforced guarantee rather than a convention.

This backend maps a CodeExecSpec onto an OpenShell policy (filesystem /
network / process / inference) and runs the entry script in a one-shot
sandbox, returning the same CodeExecResult shape as the other tiers. It slots
in behind the existing SandboxBackend Protocol + registry — no engine surgery;
the HITL gate, reaper, and tier selection are unchanged.

⚠ STATUS / INTEGRATION SEAM: OpenShell is alpha (~v0.0.57, "single-player").
The exact Gateway CLI surface + policy schema are still moving, so the two
places that touch the real contract are isolated and clearly marked:
  - ``_render_policy()``  — the policy YAML (key names follow OpenShell's four
    policy domains; validate against the installed version's schema).
  - ``_build_run_cmd()``  — the one-shot ``openshell`` invocation.
Both are env-overridable so an operator can correct flags without code edits.
Registration is OPT-IN (ENCLAVE_ENABLE_OPENSHELL=true) precisely because the
registry auto-selects the highest tier — we don't want an alpha tool silently
becoming the default code-exec path on any box that happens to have the binary.
"""

from __future__ import annotations

import os
import subprocess
import time
from typing import List, Tuple

from ...logging_config import logger
from ..sandbox import CodeExecResult, CodeExecSpec, SandboxCapabilities
from ..sandbox_fs import SandboxedFS

# The hosts an "allowlist" run may reach. Defaults to the local inference
# endpoints only (host Ollama + vLLM) — i.e. "allowlist" == "local model only".
_DEFAULT_EGRESS = "localhost:11434,localhost:8000,127.0.0.1:11434,127.0.0.1:8000"
_POLICY_FILE = "__openshell_policy__.yaml"
_ENTRY_FILE = "__entry__.py"


def _egress_allowlist() -> List[str]:
    raw = os.getenv("OPENSHELL_EGRESS_ALLOWLIST", _DEFAULT_EGRESS)
    return [h.strip() for h in raw.split(",") if h.strip()]


class OpenShellSandbox:
    name = "openshell"

    def __init__(self, binary: str = "openshell", image: str | None = None) -> None:
        self.binary = binary
        # Reuse the same hardened image the container tier builds.
        self.image = image or os.getenv(
            "OPENSHELL_SANDBOX_IMAGE",
            os.getenv("SANDBOX_CONTAINER_IMAGE", "enclave-sandbox:latest"),
        )
        # Optional gateway address (socket/URL); passed through verbatim.
        self.gateway = os.getenv("OPENSHELL_GATEWAY", "").strip()

    def capabilities(self) -> SandboxCapabilities:
        # Tier 3 → highest; the registry auto-prefers it when registered.
        # The differentiator vs tier-2 is the real "allowlist" network mode.
        return SandboxCapabilities(
            name="openshell",
            isolation_tier=3,
            network_modes=("none", "allowlist"),
            max_mem_mb=16384,
            languages=("python",),
            can_auto_run=True,
        )

    # ── Integration seam #1: policy YAML ────────────────────────────────
    def _render_policy(self, spec: CodeExecSpec) -> str:
        """Map a CodeExecSpec onto OpenShell's four policy domains.

        Key names follow OpenShell's documented policy model (filesystem /
        network / process / inference). Validate against the installed
        version's schema; this is the artifact most likely to drift.
        """
        if spec.network == "allowlist":
            allow = _egress_allowlist()
            net_lines = ["  mode: allowlist", "  allow:"] + [
                f"    - {h}" for h in allow
            ]
        else:
            net_lines = ["  mode: none"]
        lines = [
            "# Generated by Enclave OpenShellSandbox (tier-3). One-shot run.",
            "filesystem:",
            "  workdir: /work",
            "  read_only_root: true",
            "  writable:",
            "    - /work",
            "    - /tmp",
            "network:",
            *net_lines,
            "process:",
            f"  max_pids: {spec.pids}",
            "  no_new_privileges: true",
            "  cap_drop:",
            "    - ALL",
            "resources:",
            f"  memory_mb: {spec.mem_mb}",
            f"  cpus: {spec.cpus}",
            "inference:",
            # Privacy router: only the local model backend is reachable; cloud
            # LLM egress is blocked regardless of the network mode above.
            "  block_cloud: true",
            "  allow_backends:",
            *[f"    - {h}" for h in _egress_allowlist()],
        ]
        return "\n".join(lines) + "\n"

    # ── Integration seam #2: the one-shot gateway invocation ────────────
    def _build_run_cmd(self, scratch_abs: str, policy_abs: str) -> List[str]:
        """Best-effort one-shot ``openshell`` invocation.

        Targets OpenShell ~v0.0.57. Subcommand/flags are env-overridable
        (OPENSHELL_RUN_SUBCMD, default "sandbox run") so the operator can
        match the installed CLI without touching code. Validate with
        ``openshell --help``.
        """
        sub = os.getenv("OPENSHELL_RUN_SUBCMD", "sandbox run").split()
        cmd = [self.binary, *sub]
        if self.gateway:
            cmd += ["--gateway", self.gateway]
        cmd += [
            "--backend",
            os.getenv("OPENSHELL_BACKEND", "docker"),
            "--image",
            self.image,
            "--policy",
            policy_abs,
            "--mount",
            f"{scratch_abs}:/work:rw",
            "--workdir",
            "/work",
            "--rm",
            "--",
            "python",
            "-I",
            f"/work/{_ENTRY_FILE}",
        ]
        return cmd

    def execute(self, spec: CodeExecSpec) -> CodeExecResult:
        fs = SandboxedFS(spec.scratch_path, max_file_size_mb=50)
        fs.write(_ENTRY_FILE, spec.code)
        fs.write(_POLICY_FILE, self._render_policy(spec))
        policy_abs = str(fs.get_absolute_path(_POLICY_FILE))
        cmd = self._build_run_cmd(str(fs.root), policy_abs)

        t0 = time.monotonic()
        try:
            p = subprocess.run(
                cmd,
                input=spec.stdin,
                capture_output=True,
                text=True,
                # Grace beyond the in-sandbox timeout for gateway setup/teardown.
                timeout=spec.timeout_s + 15,
            )
            code, out, err, viol = p.returncode, p.stdout, p.stderr, []
        except subprocess.TimeoutExpired as e:
            code, out, err, viol = (
                -9,
                (e.stdout or "") if isinstance(e.stdout, str) else "",
                (e.stderr or "") if isinstance(e.stderr, str) else "",
                ["timeout exceeded"],
            )
        except FileNotFoundError:
            # Binary vanished after detection — fail safe, don't crash the run.
            logger.warning("openshell sandbox: binary %r not found", self.binary)
            return CodeExecResult(
                exit_code=-1,
                stdout="",
                stderr=f"openshell binary '{self.binary}' not found",
                tier_used=3,
                violations=["openshell unavailable"],
            )
        except Exception as e:  # noqa: BLE001
            logger.warning("openshell sandbox failed: %s", e)
            return CodeExecResult(
                exit_code=-1,
                stdout="",
                stderr=str(e),
                tier_used=3,
                violations=["openshell spawn failed"],
            )

        skip = {_ENTRY_FILE, _POLICY_FILE}
        produced = [r for r in fs.walk() if r not in skip]
        return CodeExecResult(
            exit_code=code,
            stdout=out[:100_000],
            stderr=err[:100_000],
            tier_used=3,
            duration_ms=(time.monotonic() - t0) * 1000,
            files_produced=produced,
            violations=viol,
        )

    # ── Detection helper ────────────────────────────────────────────────
    def ping(self) -> Tuple[bool, str]:
        """Cheap reachability probe: ``openshell --version``. Returns
        (ok, detail). Used by detect_sandboxes() to gate registration."""
        try:
            p = subprocess.run(
                [self.binary, "--version"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            if p.returncode == 0:
                return True, (p.stdout or p.stderr or "").strip()
            return False, f"exit {p.returncode}"
        except Exception as e:  # noqa: BLE001
            return False, str(e)
